### PR TITLE
AST To NSAttributedString

### PR DESCRIPTION
**Pull request by johnxnguyen**
The PR introduces changes that allow an `NSAttributedString` to be generated directly from the AST, rather than through the intermediate step of generating HTML and then instantiating the attributed string. Other changes include the new `DownStyle` class to configure and style the attributed string.

### CODE REVIEW

**Comment by iwasrobbed** [comment]
Hi @johnxnguyen 👋 This looks like quite the effort. I'd be curious to know why you took this approach (i.e. what does it offer over the alternative?). The more information you can provide, the better I can understand it if you re-open your PR.

Also, please note that all Down code (in Swift) must be licensed under MIT or it will not be acceptable to merge.

**Comment by johnxnguyen** [comment]
Hey @iwasrobbed ! My apologies, I mistakenly made the PR to your project, so you can ignore it. In any case, I'm a developer for [Wire](www.wire.com) and have been tasked with integrating markdown into the app. We found generating the attributed text directly from HTML was a bit too limited as we needed a bit more control in how the attributed text is constructed. But I'd like to take this opportunity to thank you, this framework is fantastic!

**Comment by iwasrobbed** [comment]
Glad to hear it! As I mentioned to others, also check out [BonMot](https://github.com/Raizlabs/BonMot) if you haven't already

**Comment by ianbytchek** [comment]
@johnxnguyen Looks like a lot of effort indeed. Would you consider making a PR? It would make a great feature!

cc @lilyball @kengruven

**Comment by johnxnguyen** [comment]
Hi @ianbytchek, sure I would be happy to make a PR. Though, I would first like to go over it one more and clean up some things.

**Comment by iwasrobbed** [comment]
Thanks for the offer @johnxnguyen ! We'd happily welcome a PR and also happy to add you as a collaborator

**Pull request closed without merging**
