### PR TITLE
Prevents zooming in the rendered html

### PR DESCRIPTION
**Pull request by Kumuluzz**
Addresses issue #16

I came across the need to disable zoom in my `DownView`. I thought of two solutions:
1) Disable zoom per default
2) Inject a flag when initializing the `DownView` which enables/disables zoom

This pull request implements option 1) since I imagine this being the most common

### CODE REVIEW

**Comment by iwasrobbed** [comment]
Hi @Kumuluzz 👋 

I appreciate the pull request, but I'd rather not change the default zooming for everyone. I tend to prefer configuration with sensible defaults (more like your option 2). 

Now that Down supports [instantiation with a custom bundle](https://github.com/iwasrobbed/Down/pull/27), it might be best to just do it that way for now. If a lot of people end up wanting this, I'm happy to have another look later on.

**Comment by Kumuluzz** [comment]
Hi @iwasrobbed!

Do you think it would make sense if I update my pull request to have a predefined bundle that can be specified when initializing the DownView? Fx by expanding the init method with a `allowZooming` parameter:

```swift
public init(frame: CGRect, markdownString: String, openLinksInBrowser: Bool = true, didLoadSuccessfully: DownViewClosure? = nil, allowZooming: Bool = true)
```

Otherwise I can simply update my pull request to update the documentation on how to disable zooming 😊

**Comment by iwasrobbed** [comment]
Hey @Kumuluzz! I'd prefer just keeping this as a documentation update for now versus including an additional bundle for this one scenario. If it ends up being a widely needed feature, more people are welcome to comment on this to let us know. Thanks!

**Comment by Kumuluzz** [comment]
@iwasrobbed I'll update the documentation with some instructions then. Any preferences on where to place it? Just directly in the README below `### Options`?

**Comment by iwasrobbed** [comment]
Maybe underneath the `View Rendering` section since it's specific to that area?

**Pull request closed without merging**
