### PR TITLE
Add basic Swift Package Manager support

### PR DESCRIPTION
**Pull request by zoul**
I don’t really know what I am doing here, I have just created a barebones Package.swift manifest and changed what was needed to make “swift build” to succeed while also keeping the Xcode version building. Is this something worth exploring?

### CODE REVIEW

**Comment by zoul** [comment]
I see, at least the podspec would need to be updated. (Or we could try to make SPM work with the previous file layout?)

**Comment by iwasrobbed** [comment]
Hi @zoul 👋 Thanks for your initial work on this. I'd prefer keeping the structure as-is if possible, but either way this will need to continue working for Carthage and CocoaPods across the various target devices

**Comment by zoul** [comment]
OK, I’ll try to make it work without changing the current layout :thumbsup:

**Comment by zoul** [comment]
Will try later with a new brach.

**Pull request closed without merging**
