### PR TITLE
Fix Swift module errors when used alongside Firestore

### PR DESCRIPTION
**Pull request by vzsg**
First of all, thanks for this library, I've been happily using it for months. Recently I added `Firebase/Firestore` as a dependency, which caused very cryptic build errors on a swiftmodule level. I think the author of the vague #124 might be experiencing the same issue.

Turns out the `#include "memory.h"` references in libcmark confuse the compiler – it's picking up a different memory.h from gRPC (dependency of Firestore), and everything breaks. I think it is a leftover from an earlier version of libcmark that went unnoticed.

Either way, removing those rogue references solved the issue for me, without negatively affecting anything.

---

Until this gets merged or resolved in another way, my fork can be specified as a dependency like this as a workaround:

```
pod 'Down', :git => 'https://github.com/vzsg/Down.git', :branch => 'fix-cmark-imports'
```

### CODE REVIEW

**Comment by chriszielinski** [comment]
You're right, the culprit can be found in the repository's history: https://github.com/commonmark/cmark/blob/42b07cc9c8d2e6251d190e5ea0d13fd66cb51e6d/src/memory.h

That being said, I'm not sure we should change the cmark source locally, as this may become a (_small_) reoccurring problem when updating the library in the future. Thoughts?

**Comment by vzsg** [comment]
I think cmark isn't moving too fast – a few irrelevant commits per year shouldn't be a hard factor. Especially since the sources are copied here instead of being pulled in as a submodule or some other strategy.

Two other options I could think of are:
- raising the issue in [commonmark/cmark](https://github.com/commonmark/cmark), perhaps with the very same changes in a PR. If that gets fixed there, the future risk is eliminated.
- instead of deleting lines from the sources, adding a dummy memory.h so the includes work.

**Comment by iwasrobbed** [comment]
I agree this change shouldn't be made within this repository. Please make it in the main libcmark repo and feel free to report back here once you have a resolution for it.

Others are free to use your fork

**Comment by vzsg** [comment]
Pardon me sounding salty, but what is the difference between this PR and #129? That too patched the cmark sources.

**Comment by iwasrobbed** [comment]
@vzsg That PR was accepted into upstream's master by the lead cmark engineer, and this one was not. So effectively that PR was a cherrypick from the main cmark repo.

If you can also get your changes accepted there, I'm happy to cherrypick them here as well. As you listed in your options:

>raising the issue in commonmark/cmark, perhaps with the very same changes in a PR. If that gets fixed there, the future risk is eliminated.

**Comment by vzsg** [comment]
Okay, makes sense, thanks.

**Comment by vzsg** [comment]
It is now fixed in the original repo 🙂.

**Comment by iwasrobbed** [comment]
Perfect 👌 Thanks @vzsg

**Pull request merged**
