### PR TITLE
[WIP] Proper NSAttributedString list handling on macOS (needs testing)

### PR DESCRIPTION
**Pull request by irskep**
I'm working on a simple text editor and finding that working with NSTextView isn't simple at all if you want to do anything interesting with lists.

This is one early attempt at automating list handling in this library. I don't necessarily _need_ to get this implementation in, but if you decide not to use it, then we'll need to figure out how to improve the `Styler` protocol to allow for sophisticated needs like this. IMO it would be nice to handle it automatically for users of the library. :-)

I just finished writing the code and haven't even tested it yet, but I wanted to open this PR in case it helps someone or I forget to come back to the problem.

### CODE REVIEW

**Comment by irskep** [comment]
I did a little testing and while this definitely still needs work, it does trigger list handling behavior in NSTextView.

I think the remaining work is: each time you wrap some text in a new list, you need to dig in and find all the existing paragraph styles and prepend the new list to their list arrays.

**Comment by irskep** [comment]
The tests are failing because somehow the trailing line break is getting trimmed, probably by some kind of ending-whitespace trimmer that looks at paragraph styles or something.

**Comment by iwasrobbed** [comment]
Hi @irskep 👋 I think this relates to #138 and unfortunately this feels like a pretty incomplete implementation so I'd rather not merge it. This PR will still exist if others need a reference for some sample code 👍

**Comment by irskep** [comment]
Works for me, thanks!

**Pull request closed without merging**
