### PR TITLE
Make Down portable as a built Apple Framework

### LINKED ISSUE #120: [Carthage] Missing required module 'libcmark'
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

We had this issue for example project (https://github.com/iwasrobbed/Down/issues/57) but solution was related to only example project, but not all other cases.

# Report

## What did you do?

1. Install the framework via carthage or manually to a project
2. Move sources to another directory (remove/rename it). (For carthage - `Carthage/Checkout`, for manual installing - directory with sources)

## What did you expect to happen?

The project is compiled and worked without any errors

## What happened instead?

"Missing required module 'libcmark'" error is displayed.

**Investigation**
**Why does it happen?**
Seems like when a framework project contains a module with C code and as result a modulemap to this code, then result framework will contain links to the same C code with absolute paths. You can see that inside `Down.framework/Modules/Down.swiftmodule/`. Just open any swiftmodule file with any text editor and look for old modulemap path.
I mean, this C code/headers(maybe just headers, not sure about that) should be placed at the same place for using the framework, otherwise framework won't find this C-module (in this case - cmark)

**Workaround**
Only workaround what I've found is to copy cmark folder(folder with C code) inside your project (where you have to use Down.framework) and configure Import Paths to this directory. Then, when Down.framework have to find cmark module, it will use the project settings (module is configured and load to the project already).
So, either do not remove `Checkout` directory for carthage (because framework will look for `cmark` module there) and as result do not use any caches for carthage (like rome), or add `cmark` directory to your project and configure `Import Paths`.

**Bridging-Header solution**
If we remove using modulemap and add Bridging-Header to the project, then this case will work only when we don't have `Checkouts` folder. But at the same time, it won't work if sources are there (if you build it through carthage and do not remove `Checkouts` directory). In that case you will have `Failed to import bridging header` error when trying to build your project.

### PR DESCRIPTION
**Pull request by erikkerber**
Resolves #120 

The Down library as-is does not generate a "portable" framework, as described very well in [this blog post](https://medium.com/bumble-tech/bundling-c-library-in-swift-framework-3d9dae950774). The result is that anyone who attempts to build and consume Down as an Apple Framework needs to add the cmark directory from source into the `SWIFT_INCLUDE_PATHS`

```
SWIFT_INCLUDE_PATHS = $(inherited) $(PROJECT_DIR)/Carthage/Checkouts/down/Source/cmark
```

Additionally, having matching module names and types exposes the Down library to this bug: https://bugs.swift.org/browse/SR-14195.

This only manifests when the framework is built for distribution, but it does make building with library evolution/`BUILD_LIBRARY_FOR_DISTRIBUTION = YES` impossible.

This change does the following:
- Builds cmark as a clang submodule using a custom modulemap for both Down/cmark
- Renames the module to "DownLib" from "Down" to avoid SR-14195

The renaming of the module is critical for portability, but could easily be dropped from this PR if that's something that is too aggressive at the moment.

### CODE REVIEW

**Comment by larryonoff** [comment]
I have an issue when importing this library into my Swift Package. This PR fixes this.

**Comment by johnxnguyen** [comment]
There's some issues with Travis CI that need working out, I'll fix it this weekend.

**Comment by larryonoff** [comment]
I'll make PR today. Maybe there're a bit simpler solution.

**Comment by larryonoff** [comment]
Please see https://github.com/johnxnguyen/Down/pull/268

**Comment by MarcoEidinger** [comment]
@johnxnguyen any plans to merge this PR? Being able to build a working xcframework would be really helpful!

**Comment by larryonoff** [comment]
> @johnxnguyen any plans to merge this PR? Being able to build a working xcframework would be really helpful!

I just copied Down to our local repos for the moment. :(

**Comment by johnxnguyen** [comment]
The test target is failing to build, I would like to resolve this first before merging.

**Comment by erikkerber** [comment]
Sorry friends as I did not steward this to completion.

@johnxnguyen I rebased off `master` to see if the error still reproduced and, if so, actually get a CI result that hasn't been time expired.

If you think this is better off just being closed, that is fine as well. We now consume and build Down via Bazel, so the portable pre-built framework is no longer "needed" by us. Happy to land this if it helps others though.

**Pull request closed without merging**
