### PR TITLE
#6 macOS Support

### LINKED ISSUE #6: Add OS X support
Welcoming any pull requests to add OS X support for those who need it.

### PR DESCRIPTION
**Pull request by 128keaton**
Adds support for macOS (resolves #6)

### CODE REVIEW

**Comment by iwasrobbed** [comment]
Thanks @128keaton ! Mind describing the project changes real quick? Might be easier than me trying to visually see what's changed

**Comment by 128keaton** [comment]
@iwasrobbed I actually changed very little. I added a new Target for macOS, then just allowed 'ownership' of the needed files to the target. I shimmed code in two files to allow the compiler to use the correct frameworks for each platform, and the correct line of code to open the URL.

**Comment by 128keaton** [comment]
err I didn't want those to be pulled..wtf Github.

**Comment by iwasrobbed** [comment]
Thanks @128keaton! (btw, you'd need to fork your local branch if you don't want that commit showing up here; otherwise, any commit to your `master` will be on this PR)

**Comment by iwasrobbed** [comment]
I think the https://github.com/iwasrobbed/Down/pull/25/commits/642972adb2a4cda3acec81e56400b23ead3727d9 commit is fine to keep, I'll have a look later

**Comment by 128keaton** [comment]
@iwasrobbed okay I'll see if I can figure it out. I've never used tests or travis before. If anyone else who knows how to write tests just makes the changes in their branch I'll close this request and you can use theirs

**Comment by iwasrobbed** [comment]
@128keaton Ah no worries, no need to write new tests most likely (we just need to execute the existing tests against your new macOS target). 

The best thing to do is just run that tests command locally on your `Terminal` cli for the iOS target and then adapt it so we can also add one for the macOS target (like that other example I showed was doing)

Existing iOS test command:

```bash
set -o pipefail && xcodebuild test -project Down.xcodeproj -scheme "Down-iOS" -destination "platform=iOS Simulator,name=iPhone 5,OS=9.3" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c
```

I imagine the macOS version would look like

```bash
set -o pipefail && xcodebuild test -project Down.xcodeproj -scheme "Down-macOS" -sdk macosx -destination "platform=OS X,arch=x86_64" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c
```

If that works locally on your computer, we *hopefully* shouldn't have problems just appending it to our `.travis.yml` file and getting it passing.

Does that help clarify it?

**Comment by 128keaton** [comment]
@iwasrobbed well I can't get OS X tests to run, at all, `Early unexpected exit, operation never finished bootstrapping - no restart will be attempted`. I've added the OS X framework to the testing binaries, tried codesigning, cleaning, relaunching Xcode, rebooting. Stumped.

**Comment by 128keaton** [comment]
Okay, I created a tests target for OS X (oops) and the command works if I specify the testing scheme.

**Comment by iwasrobbed** [comment]
@128keaton Welcome to the fun (but necessary) world of testing :) If things are working as planned, feel free to add that new command to the travis script and commit the changes and the PR will re-run w/ those tests

**Comment by 128keaton** [comment]
Yup. I need to start doing this with all of my projects. Currently learning Travis. Let me check it out and I'll push the test branch

**Comment by 128keaton** [comment]
Lets see if this works!

**Comment by iwasrobbed** [comment]
Travis is really finicky and looks like it errored out for internal reasons, so I restarted the build to see if it'd clear itself 🍿 👀

**Comment by iwasrobbed** [comment]
Look at that, worked like a charm. Thanks again (and also thanks for your patience & for rebasing) @128keaton !

**Comment by 128keaton** [comment]
Yeah haha don't worry about it. Glad it works!

**Pull request merged**
