### PR TITLE
Bump Swift to 5.0

### PR DESCRIPTION
**Pull request by larryonoff**

### CODE REVIEW

**Comment by J2Marin** [comment]
@larryonoff don't forget updating macos image value on the travis config file to `osx_image: xcode10.2 ` which brings support to swift5, otherwise build will fail:
https://github.com/iwasrobbed/Down/blob/3d044c766b36f9e5d3460d625e16c08a55bba565/.travis.yml#L1

**Comment by larryonoff** [comment]
@J2Marin thanks for mentioning. Fixed it already.

**Comment by iwasrobbed** [comment]
@larryonoff I'm hesitant to merge this for now since it will force everyone to update to Xcode 10.2. Any reason this would be needed immediately? (since you can still compile Swift 4.x libs in Swift 5 projects)

**Comment by larryonoff** [comment]
@iwasrobbed I've created PR with more elegant solution on supporting Swift >4, see #144.

**Comment by larryonoff** [comment]
@iwasrobbed

> @larryonoff I'm hesitant to merge this for now since it will force everyone to update to Xcode 10.2. Any reason this would be needed immediately? (since you can still compile Swift 4.x libs in Swift 5 projects)

I think you should not hesitant since if someone wants Swift ~4 they can use previous versions of Down.

Swift 5 compiler is really fast for me. So It should be one more point to update. :)

**Comment by iwasrobbed** [comment]
This PR misses a few areas, so closing it out in favor of https://github.com/iwasrobbed/Down/pull/145

**Pull request closed without merging**
