### PR TITLE
Add the ability to initialise a DownView using a custom template bundle

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR introduces an extra optional parameter when initialising `DownView` that allows the caller to specify a custom template bundle.

### CODE REVIEW

**Comment by tonyarnold** [comment]
Not at all! I'll add a test when I'm next at my Mac 👍

**Comment by tonyarnold** [comment]
Do the test targets work for you? I can't get either the iOS or the macOS targets to build, let alone run.

**Comment by iwasrobbed** [comment]
@tonyarnold I haven't tested locally, but they ran successfully as part of this PR

**Comment by tonyarnold** [comment]
@iwasrobbed I've added a single test (along with a test bundle fixture) in addc2350d756892c3669a196cdd02c196dea7ed4. Let me know if you need more!

**Comment by iwasrobbed** [comment]
Looks great, thanks again @tonyarnold !

**Comment by tonyarnold** [comment]
You're welcome - thanks for the great library!

**Pull request merged**
